### ISSUE TITLE
cant find address

### ISSUE THREAD

**Issue by BoKKeR** [ewels/hemnet-commuter#7]
It is exactly what I need and i actually wanted to build something similar but found your solution when searching for hemnet rss. For some reason I cant seem to be able to get any address accepted. Is this because of my formatting or did google change their matrix api

**Comment by ewels** [comment]
Hi @BoKKeR,

It looks like this is due to the changes in the matrix API. Specifically that it no longer works for free without credit card details. The error response returned from Google is as follows:

> `status`: `"REQUEST_DENIED"`
> `error_message`: You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started

If you fork the repo and edit the code to use your own Google API key in this line:
https://github.com/ewels/hemnet-commuter/blob/ae2ed9049f137dc9112037e860f2a2838c780535/index.html#L121
..then it might work?

Let me know how you get on. If the code is still valid then I could always update this so that the running version at http://beta.tallphil.co.uk/hemnet-commuter/ works if you enter a valid Google API key or something.

Phil

**Comment by BoKKeR** [comment]
I managed to get it running on my server with my own key. Now only the commute times dont show at all.

**Comment by ewels** [comment]
Nice! Not sure for the commute times sorry. The code hasn't been touched for a while now so it might well be that stuff has changed upstream. Let me know if you get it working..!

**Comment by ewels** [comment]
Hi @BoKKeR,

You're in luck with your timing, as I am actually also thinking of moving soon so wanted to get this working again for myself 😉 

I've just pushed a rewrite to `master` which completely removes the Google Maps API. The map is now plotted using [Leaflet.js](https://leafletjs.com/) and the address geocoding + travel times are done using the [Travel Times platform API](https://www.traveltimeplatform.com/).

It's still missing a few features and a bit of polish, but the basic functionality is now working I think, so should hopefully be useful to you. I haven't deployed it to the public server yet though, so you'll need to run it yourself for now. Keep an eye out for updates as I hope to do some more soon, and any suggestions for improvements welcome!

Let me know how you get on..

Phil
